livraria/urls.py
from django.urls import path

from livraria import views

urlpatterns = [
    path('', views.index, name='index'),
    # path('', views.IndexTemplateView.as_view(), name='index'),
    path('categorias', views.CategoriaListView.as_view(), name='categorias'),
    path('categoria/<int:pk>', views.CategoriaDetailView.as_view(), name='detalhe-categoria'),
    path('autores', views.AutoresListView.as_view(), name='autores'),
    path('autor/<int:pk>', views.AutoresDetailView.as_view(), name='detalhe-autor'),
]

setup/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('livraria.urls')),
]

livraria/models.py
from django.db import models
from django.urls import reverse


class Categoria(models.Model):
    nome = models.CharField(max_length=50, unique=True, null=False)

    def __str__(self):
        return self.nome

    def get_absolute_url(self):
        return reverse('detalhe-categoria', kwargs={'pk': self.pk})

    objects = models.Manager()


class Editora(models.Model):
    nome = models.CharField(max_length=255, unique=True, null=False)
    endereco = models.TextField(null=False)
    telefone = models.CharField(max_length=20)

    def __str__(self):
        return self.nome

    def get_absolute_url(self):
        return reverse('editora-detail', kwargs={'pk': self.pk})

    objects = models.Manager()


class Autor(models.Model):
    nome = models.CharField(max_length=255, null=False)
    email = models.CharField(max_length=255, unique=True, null=False)
    bio = models.TextField(null=False)
    telefone = models.CharField(max_length=20)

    def __str__(self):
        return self.nome

    def get_absolute_url(self):
        return reverse('detalhe-autor', kwargs={'pk': self.pk})

    objects = models.Manager()


class Livro(models.Model):
    titulo = models.CharField(null=False)
    isbn = models.CharField(max_length=20, unique=True, null=False)
    codigo = models.CharField(max_length=10, unique=True, null=False)
    paginas = models.IntegerField(null=False)
    ano = models.IntegerField(null=False)
    resumo = models.TextField(null=False)
    categoria = models.ForeignKey(Categoria, on_delete=models.RESTRICT)
    editora = models.ForeignKey(Editora, on_delete=models.RESTRICT)
    autor = models.ForeignKey(Autor, on_delete=models.RESTRICT)

    def __str__(self):
        return self.titulo

    def get_absolute_url(self):
        return reverse('detalhe-livro', kwargs={'pk': self.pk})

    objects = models.Manager()

livraria/forms.py
from django import forms

from livraria.models import Categoria, Editora, Autor


class CategoriaForm(forms.ModelForm):
    class Meta:
        model = Categoria
        fields = ['nome']


class EditoraForm(forms.ModelForm):
    class Meta:
        model = Editora
        fields = ['nome', 'endereco', 'telefone']


class AutorForm(forms.ModelForm):
    class Meta:
        model = Autor
        fields = ['nome', 'email', 'bio', 'telefone']

livraria/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, TemplateView

from livraria.models import Livro, Autor, Categoria


def index(request):
    quantidade_livros = Livro.objects.all().count()
    quantidade_autores = Autor.objects.all().count()

    context = {
        'quantidade_livros': quantidade_livros,
        'quantidade_autores': quantidade_autores,
    }

    return render(request, 'index.html', context=context)


# class IndexTemplateView(TemplateView):
#     template_name = 'index.html'
#
#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         context['quantidade_livros'] = Livro.objects.all().count()
#         context['quantidade_autores'] = Autor.objects.all().count()
#         return context


class CategoriaListView(ListView):
    model = Categoria
    template_name = 'categorias.html'


class CategoriaDetailView(DetailView):
    model = Categoria
    template_name = 'categoria.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        livros = Livro.objects.filter(categoria=context.get('categoria').id)
        context["livros_list"] = livros
        return context


class AutoresListView(ListView):
    model = Autor
    template_name = 'autores.html'


class AutoresDetailView(DetailView):
    model = Autor
    template_name = 'autor.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        livros = Livro.objects.filter(autor_id=context.get('autor').id)
        context["livros_list"] = livros
        return context

livraria/templates/autor.html
{% extends "base_template.html" %}

{% block title %}<title>Autor | Livraria Online</title>{% endblock %}

{% block content %}
  <div class="row">
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'index' %}">Home</a></li>
        <li class="breadcrumb-item"><a href="{% url 'autores' %}">Autores</a></li>
        <li class="breadcrumb-item active" aria-current="page">{{ autor.nome }}</li>
      </ol>
    </nav>
  </div>

  <div class="row">
    <div class="col-md-12 mb-3">
      <h4 class="card-title">{{ autor.nome }}</h4>
    </div>
  </div>

  {% include 'lista-livros.html' with livros=livros_list detalhe_autor=True %}

{% endblock %}

livraria/templates/autores.html
{% extends "base_template.html" %}

{% block title %}<title>Autores | Livraria Online</title>{% endblock %}

{% block content %}
  <div class="row">
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'index' %}">Home</a></li>
        <li class="breadcrumb-item active" aria-current="page">Autores</li>
      </ol>
    </nav>
  </div>

  <div class="row">
    <div class="col-md-12 mb-3">
      <h4 class="card-title">Autores</h4>
    </div>
  </div>

  <div class="row">
    {% if autor_list %}
      {% for autor in autor_list %}
        <div class="col-md-4 mb-5">
          <div class="card" style="width: 18rem;">
            <img src="/static/images/autor.png" class="card-img-top" alt="Foto do autor">
            <div class="card-body">
              <h5 class="card-title">{{ autor.name }}</h5>
              <p class="card-text">{{ autor.bio }}</p>
              <a href="{{ autor.get_absolute_url }}" class="btn btn-primary">Ver livros</a>
            </div>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <p>Não encontrei nenhum autor cadastrado!</p>
    {% endif %}
  </div>

{% endblock %}

livraria/templates/base_template.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% block title %}<title>Livraria Online</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <!-- Nosso arquivo CSS estático -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>

  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand">Livraria Online</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a class="nav-link active" aria-current="page" href="{% url 'index' %}">Home</a>
          <a class="nav-link" href="{% url 'categorias' %}">Categorias</a>
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Livros</a>
          <a class="nav-link" href="{% url 'autores' %}">Autores</a>
        </div>
      </div>
      <form class="d-flex">
        {% if user.is_authenticated %}
          <a href="{% url 'admin:index' %}" class="btn btn-outline-secondary" target="_blank">Admin</a>
        {% else %}
          <a href="{% url 'admin:index' %}" class="btn btn-outline-secondary" target="_blank">Login</a>
        {% endif %}
      </form>
    </div>
  </nav>

  <div class="container mt-3">
    {% block content %}<!--  Código default (geralmente em branc)  -->{% endblock %}
  </div>
</body>
</html>

livraria/templates/categoria.html
{% extends "base_template.html" %}

{% block title %}<title>Categoria | Livraria Online</title>{% endblock %}

{% block content %}
  <div class="row">
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'index' %}">Home</a></li>
        <li class="breadcrumb-item"><a href="{% url 'categorias' %}">Categorias</a></li>
        <li class="breadcrumb-item active" aria-current="page">{{ categoria.nome }}</li>
      </ol>
    </nav>
  </div>

  <div class="row">
    <div class="col-md-12 mb-3">
      <h4 class="card-title">{{ categoria.nome }}</h4>
    </div>
  </div>

  {% include 'lista-livros.html' with livros=livros_list %}

{% endblock %}

livraria/templates/categorias.html
{% extends "base_template.html" %}

{% block title %}<title>Categorias | Livraria Online</title>{% endblock %}

{% block content %}
  <div class="row">
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'index' %}">Home</a></li>
        <li class="breadcrumb-item active" aria-current="page">Categorias</li>
      </ol>
    </nav>
  </div>

  <div class="row">
    <div class="col-md-12 mb-3">
      <h4 class="card-title">Categorias</h4>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12 mb-3">
      {% if categoria_list %}
        <div class="list-group">
          {% for categoria in categoria_list %}
            <a href="{{ categoria.get_absolute_url }}" class="list-group-item list-group-item-action">{{ categoria.nome }}</a>
          {% endfor %}
        </div>
      {% else %}
        <p>Não encontrei nenhuma categoria cadastrada!</p>
      {% endif %}
    </div>
  </div>

{% endblock %}

livraria/templates/index.html
{% extends "base_template.html" %}

{% block title %}<title>Home | Livraria Online</title>{% endblock %}

{% block content %}
  <div class="row">
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item active" aria-current="page">Home</li>
      </ol>
    </nav>
  </div>

  <div class="row">
    <div class="col-md-12 mb-3">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Bem-vindo a Livraria Online!</h5>
          <p class="card-text">Veja um resumo do nosso catálogo atualmente e aproveite!</p>
        </div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item">{{ quantidade_livros }} Livros</li>
          <li class="list-group-item">{{ quantidade_autores }} Autores</li>
        </ul>
        <div class="card-body">
          <div class="imagem-livros"></div>
        </div>
      </div>
    </div>
  </div>

{% endblock %}

livraria/templates/lista-livros.html
<div class="row">
  {% if livros %}
      {% for livro in livros %}
        <div class="col-md-4 mb-5">
          <div class="card" style="width: 25rem;">
            <div class="card-body">
              <h5 class="card-title">{{ livro.titulo }}</h5>
              {% if not detalhe_autor %}
                <h6 class="card-subtitle mb-2 text-muted">{{ livro.autor }}</h6>
              {% endif %}
              <p class="card-text">{{ livro.resumo }}</p>
              <a href="#" class="card-link">Detalhes</a>
              {% if not detalhe_autor %}
                <a href="{% url 'detalhe-autor' pk=livro.autor.id %}" class="card-link">Autor</a>
              {% endif %}
            </div>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <p>Não encontrei nenhum livro deste autor!</p>
    {% endif %}
</div>